theme: jekyll-theme-minimal

title: "Rafael Gallardo-García"
logo: /assets/imgs/pp1.jpg
description: >
  Abstract: <br> Hi, my name is Rafael and this is my personal web page, here here you can find information about my academic trajectory, projects, and publications. <br>

  Keywords:
    Natural Language Processing,
    Computer Vision,
    Multimodal Deep Learning,
    Deep Learning,
    Machine Learning.
