theme: jekyll-theme-minimal

title: Rafael Gallardo-García
description: My personal web page: here you can find information about my academic
              trajectory, projects, and publications.
logo: /assets/imgs/pp1.jpg
