remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Rafael Gallardo"
logo: /assets/imgs/pp0.jpg
description: Hi, my name is Rafael, this is my personal webpage, here you can find some info about me, and different ways to contact me.
